# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
warnings_are_errors: true

r_binary_packages:
  - Rcpp

notifications:
  email:
    on_success: change
    on_failure: change
